#!/usr/bin/env python3
"""
Process voice memo transcriptions from GitHub Issues.

This script:
1. Reads the transcript from the issue body
2. Loads editorial context (persona, guidelines, knowledge base)
3. Calls Claude to clean, analyze, and suggest placement
4. Outputs analysis to file for workflow to post as comment
5. Sets step outputs for workflow to use

DOES NOT: Make direct GitHub API calls for comments/labels (workflow handles that)
"""

import os
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.utils.github_client import (  # noqa: E402
    get_github_client,
    get_issue,
    get_repo,
)
from scripts.utils.knowledge_base import load_editorial_context  # noqa: E402
from scripts.utils.llm_client import (  # noqa: E402
    build_editorial_prompt,
    call_editorial,
)


def set_output(name: str, value: str):
    """Set a step output for the GitHub Actions workflow."""
    output_file = os.environ.get("GITHUB_OUTPUT")
    if output_file:
        with open(output_file, "a") as f:
            # Handle multiline values
            if "\n" in value:
                import uuid

                delimiter = uuid.uuid4().hex
                f.write(f"{name}<<{delimiter}\n{value}\n{delimiter}\n")
            else:
                f.write(f"{name}={value}\n")


def main():
    # Get environment variables
    issue_number = int(os.environ.get("ISSUE_NUMBER", 0))
    if not issue_number:
        print("ERROR: ISSUE_NUMBER not set")
        sys.exit(1)

    # Initialize clients
    gh = get_github_client()
    repo = get_repo(gh)
    issue = get_issue(repo, issue_number)

    # Get transcript from issue body
    transcript = issue.body or ""
    if not transcript.strip():
        # Output error comment
        error_comment = "No transcript found in issue body. Please add the voice memo transcript."
        Path("output").mkdir(exist_ok=True)
        Path("output/analysis-comment.md").write_text(error_comment)
        set_output("success", "false")
        set_output("error", "No transcript in issue body")
        sys.exit(1)

    # Load editorial context
    print("Loading editorial context...")
    context = load_editorial_context(repo)

    # Build the analysis prompt
    task = """Analyze this voice memo transcript and provide:

1. **Cleaned Transcript**: Fix grammar, punctuation, remove filler words (um, uh, like, you know), but preserve the author's voice and meaning exactly. Do not add new content or change the meaning.

2. **Content Analysis**: What is this about? What themes, topics, or ideas are present? How does it relate to the book's central themes?

3. **Suggested Placement**: Based on the existing chapters, where might this content fit?
   - Should it be added to an existing chapter? Which one and where?
   - Should it become a new chapter or section?
   - Is it notes/ideas for later development?

4. **Editorial Notes**:
   - What's working well in this content?
   - What needs clarification or expansion?
   - Questions for the author about intent or meaning

5. **Ready for PR?**: Can this be integrated now, or does it need author input first?

Format your response with clear ### headers for each section."""

    prompt = build_editorial_prompt(
        persona=context["persona"],
        guidelines=context["guidelines"],
        glossary=context["glossary"],
        knowledge_base=context["knowledge_formatted"],
        chapter_list=context["chapters"],
        task=task,
        content=transcript,
    )

    # Call LLM with reasoning enabled
    print("Calling LLM for editorial analysis (with reasoning)...")
    try:
        llm_response = call_editorial(prompt)
        print(f"LLM call complete: {llm_response.usage.format_compact()}")
        if llm_response.has_reasoning():
            print("Editorial reasoning captured for transparency")
    except Exception as e:
        error_comment = f"Error calling AI: {str(e)}"
        Path("output").mkdir(exist_ok=True)
        Path("output/analysis-comment.md").write_text(error_comment)
        set_output("success", "false")
        set_output("error", str(e))
        sys.exit(1)

    # Format the comment with reasoning explanation
    reasoning_section = llm_response.format_editorial_explanation()

    comment = f"""## AI Editorial Analysis

{llm_response.content}

---

### Next Steps

**To integrate this content:**
1. Reply with any feedback or answers to my questions above
2. Specify placement: `@ai-editor place in chapter-name.md`
3. When ready: `@ai-editor create PR`

**Or if this isn't ready:**
- Close this issue if you want to discard it
- Add `awaiting-author` label if you need to think about it
- Just reply with questions or direction

{reasoning_section}

---
*This analysis was generated by AI Book Editor. I'm here to help, not to impose—your voice is what matters.*

<sub>{llm_response.usage.format_summary()}</sub>
"""

    # Output to file for workflow to use
    Path("output").mkdir(exist_ok=True)
    Path("output/analysis-comment.md").write_text(comment)

    # Set step outputs
    set_output("success", "true")
    set_output("has_analysis", "true")

    print(f"Successfully processed issue #{issue_number}")
    print(f"Analysis written to output/analysis-comment.md")


if __name__ == "__main__":
    main()
